blockExoticSubdeps: true
minimumReleaseAge: 4320
allowBuilds:
  classic-level: false
  '@parcel/watcher': false
  postinstall-postinstall: false
  esbuild: true
  '@league-of-foundry-developers/foundry-vtt-types@https://codeload.github.com/League-of-Foundry-Developers/foundry-vtt-types/tar.gz/2315d2385e256f8e7011667683f0859f1f769fdf': true
peerDependencyRules:
  allowedVersions:
    "@pixi/basis>@pixi/assets": "*"
    "@pixi/basis>@pixi/core": "*"
  ignoreMissing:
    - "@pixi/compressed-textures"
    - "@pixi/particle-emitter"
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080

